// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsApi.Models;

#nullable disable

namespace ProductsApi.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20260319234927_NewTable1")]
    partial class NewTable1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("ProductsApi.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IsActive = true,
                            Price = 60000m,
                            ProductName = "Iphone 14"
                        },
                        new
                        {
                            ProductId = 2,
                            IsActive = true,
                            Price = 50000m,
                            ProductName = "Samsung S23"
                        },
                        new
                        {
                            ProductId = 3,
                            IsActive = true,
                            Price = 30000m,
                            ProductName = "Xiaomi 13"
                        },
                        new
                        {
                            ProductId = 4,
                            IsActive = true,
                            Price = 90000m,
                            ProductName = "Macbook Pro"
                        },
                        new
                        {
                            ProductId = 5,
                            IsActive = true,
                            Price = 8000m,
                            ProductName = "Airpods"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
